### ISSUE TITLE
Distribution: bundle app with flet pack

### ISSUE THREAD

**Issue by clstaudt** [tuttle-dev/tuttle#113]

**Comment by clstaudt** [comment]
```shell
Traceback (most recent call last):
  File "app/app.py", line 14, in <module>
ModuleNotFoundError: No module named 'auth'
[63854] Failed to execute script 'app' due to unhandled exception: No module named 'auth'
[63854] Traceback:
Traceback (most recent call last):
  File "app/app.py", line 14, in <module>
ModuleNotFoundError: No module named 'auth'

```

- [ ] turn app code into a proper module structure
