### ISSUE TITLE
Bug: Preferences screen not accesible after refactoring

### ISSUE THREAD

**Issue by clstaudt** [tuttle-dev/tuttle#118]
The Preferences screen is no longer accessible via the menu button.

Exception stack trace:

```python
Exception in thread Thread-22 (on_view_settings_clicked):
Traceback (most recent call last):
  File "/Users/cls/miniforge3/envs/tuttle/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/Users/cls/miniforge3/envs/tuttle/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/cls/Documents/Work/Projects/PrototypeFund/Dev/tuttle/app/home/view.py", line 495, in on_view_settings_clicked
    self.navigate_to_route(PREFERENCES_SCREEN_ROUTE)
  File "/Users/cls/Documents/Work/Projects/PrototypeFund/Dev/tuttle/app/app.py", line 166, in change_route
    self.page.go(newRoute)
  File "/Users/cls/miniforge3/envs/tuttle/lib/python3.10/site-packages/flet/page.py", line 336, in go
    self.__on_route_change.handler(
  File "/Users/cls/miniforge3/envs/tuttle/lib/python3.10/site-packages/flet/event_handler.py", line 16, in handler
    h(r)
  File "/Users/cls/Documents/Work/Projects/PrototypeFund/Dev/tuttle/app/app.py", line 193, in on_route_change
    route_view_wrapper = self.routeParser.parse_route(pageRoute=route.route)
  File "/Users/cls/Documents/Work/Projects/PrototypeFund/Dev/tuttle/app/app.py", line 302, in parse_route
    on_theme_changed=self.app.on_theme_changed,
AttributeError: 'TuttleApp' object has no attribute 'on_theme_changed'. Did you mean: 'on_route_change'?
```

**Comment by vlad-ed-git** [comment]
fixed
