### ISSUE TITLE
Bug: app start broken

### ISSUE THREAD

**Issue by clstaudt** [tuttle-dev/tuttle#124]
2023-01-10 17:48:45.808 | DEBUG    | core.abstractions:query:121 - querying <class 'tuttle.model.User'>
exception raised @splash_screen.did_mount (sqlite3.OperationalError) no such column: user.profile_photo
[SQL: SELECT user.id, user.name, user.subtitle, user.website, user.email, user.phone_number, user.profile_photo, user.address_id, user."VAT_number", user.icloud_account_id, user.bank_account_id, user.logo 
FROM user]
(Background on this error at: https://sqlalche.me/e/14/e3q8)

**Comment by clstaudt** [comment]
@vlad-ed-git  please fix

**Comment by vlad-ed-git** [comment]
@Christian Staudt ***@***.***> please merge with my latest push
before you proceed.

**Comment by clstaudt** [comment]
@vlad-ed-git  I have your latest version, it's still broken

**Comment by clstaudt** [comment]
```shell
2023-01-10 17:57:38.409 | INFO     | core.abstractions:__init__:112 - Creating TimeTrackingDataSource with db_path: sqlite:////Users/cls/.tuttle/tuttle.db
screen has (None,)
page scroll type (None,)
Exception in thread Thread-13 (on_skip_clicked):
Traceback (most recent call last):
  File "/Users/cls/miniforge3/envs/tuttle/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/Users/cls/miniforge3/envs/tuttle/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/cls/Documents/Work/Projects/PrototypeFund/Dev/tuttle/app/auth/view.py", line 174, in on_skip_clicked
    self.on_logged_in()
  File "/Users/cls/Documents/Work/Projects/PrototypeFund/Dev/tuttle/app/auth/view.py", line 338, in on_logged_in
    self.navigate_to_route(res_utils.HOME_SCREEN_ROUTE)
  File "/Users/cls/Documents/Work/Projects/PrototypeFund/Dev/tuttle/app/app.py", line 181, in change_route
    self.page.go(newRoute)
  File "/Users/cls/miniforge3/envs/tuttle/lib/python3.10/site-packages/flet/page.py", line 336, in go
    self.__on_route_change.handler(
  File "/Users/cls/miniforge3/envs/tuttle/lib/python3.10/site-packages/flet/event_handler.py", line 16, in handler
    h(r)
  File "/Users/cls/Documents/Work/Projects/PrototypeFund/Dev/tuttle/app/app.py", line 208, in on_route_change
    route_view_wrapper = self.route_parser.parse_route(pageRoute=route.route)
  File "/Users/cls/Documents/Work/Projects/PrototypeFund/Dev/tuttle/app/app.py", line 312, in parse_route
    return self.get_page_route_view(routePath.route, view=screen)
  File "/Users/cls/Documents/Work/Projects/PrototypeFund/Dev/tuttle/app/app.py", line 249, in get_page_route_view
    view_container = View(
  File "/Users/cls/miniforge3/envs/tuttle/lib/python3.10/site-packages/flet/view.py", line 58, in __init__
    self.scroll = scroll
  File "/Users/cls/miniforge3/envs/tuttle/lib/python3.10/site-packages/flet/view.py", line 203, in scroll
    self.__set_scroll(value)
  File "<@beartype(flet.view.View.__set_scroll) at 0x106295c60>", line 54, in __set_scroll
beartype.roar.BeartypeCallHintParamViolation: @beartyped flet.view.View.__set_scroll() parameter value=(None,) violates type hint typing.Optional[typing.Literal[None, True, False, 'none', 'auto', 'adaptive', 'always', 'hidden']], as tuple (None,):
* Not <class "builtins.NoneType">.
* Tuple (None,) not instance of <class "builtins.NoneType">, bool, bool, str, str, str, str, or str.
* ```

**Comment by vlad-ed-git** [comment]
@Christian Staudt ***@***.***> this is fixed on latest commit : `fix:
bugs after refactoring` . You should be able to proceed after pulling from
this

**Comment by vlad-ed-git** [comment]
@clstaudt this should be fixed now . post commit `fix: bugs after refactoring``

**Comment by vlad-ed-git** [comment]
@clstaudt please confirm and close issue if fixed
