### ISSUE TITLE
Bug: Assertion error from Preferences screen

### ISSUE THREAD

**Issue by clstaudt** [tuttle-dev/tuttle#128]
```shell
Exception in thread Thread-54 (save_value):
Traceback (most recent call last):
  File "/Users/cls/miniforge3/envs/tuttle/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/Users/cls/miniforge3/envs/tuttle/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/cls/Documents/Work/Projects/PrototypeFund/Dev/tuttle/app/core/local_storage_impl.py", line 18, in save_value
    self.page.client_storage.set(
  File "/Users/cls/miniforge3/envs/tuttle/lib/python3.10/site-packages/flet/client_storage.py", line 11, in set
    assert jv is not None
AssertionError
```

**Comment by vlad-ed-git** [comment]
@clstaudt fixed
