### ISSUE TITLE
Bug: Implementing is active on Contract, and Project models

### ISSUE THREAD

**Issue by vlad-ed-git** [tuttle-dev/tuttle#134]

**Comment by vlad-ed-git** [comment]
@clstaudt currently. is_active throws this error 
'>' not supported between instances of 'NoneType' and 'datetime.date'

**Comment by clstaudt** [comment]
@vlad-ed-git Okay, will have a look. Full stack trace for bug reports please.

**Comment by vlad-ed-git** [comment]
Getting 'list' object has no attribute 'where', from the contracts' data source. @clstaudt

**Comment by clstaudt** [comment]
Copy/paste the complete Python interpreter stack trace please 😄

**Comment by vlad-ed-git** [comment]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/vlad/Desktop/vlad/tuttle/app/contracts/view.py", line 561, in <lambda>
    on_click=lambda e: onClick(state),
  File "/Users/vlad/Desktop/vlad/tuttle/app/contracts/view.py", line 583, in on_filter_button_clicked
    self.onStateChangedCallback(state)
  File "/Users/vlad/Desktop/vlad/tuttle/app/contracts/view.py", line 1075, in on_filter_contracts
    self.contracts_to_display = self.intent_handler.get_active_contracts()
  File "/Users/vlad/Desktop/vlad/tuttle/app/contracts/intent.py", line 112, in get_active_contracts
    if c.is_active():
  File "/Users/vlad/Desktop/vlad/tuttle/tuttle/model.py", line 305, in is_active
    return self.end_date > today
TypeError: '>' not supported between instances of 'NoneType' and 'datetime.date'

**Comment by vlad-ed-git** [comment]
`self.intent_handler.get_active_contracts()` calls `is_active()` on each contract model and that's where an error occurs.

**Comment by clstaudt** [comment]
possible quick fix (can't code on iPad unfortunately) @vlad-ed-git 


    def is_active(self) -> bool:
        if self.end_date:
            today = datetime.date.today()
            return self.end_date > today
        else:
            return True

**Comment by clstaudt** [comment]
Project.end_date cannot be none as per the model definition. So there is no bug in Project.is_active

**Comment by vlad-ed-git** [comment]
Okay I will add this

**Comment by vlad-ed-git** [comment]
@clstaudt fixed
