### ISSUE TITLE
Distribution: Refactor into functioning Python package

### ISSUE THREAD

**Issue by clstaudt** [tuttle-dev/tuttle#216]
Distributing the project requires that the entire code is packaged as a proper Python package. This is currently not the case for the  `app` code.

To verify that Python package is properly structured:

1. `cd <project_dir>`
2. `pip install -e .`
3. `cd <out_of_project_dir>`
4. `python`
5. `import tuttle`

To verify that the Package can be packaged as an executable:

1.  `flet pack tuttle/app/app.py --name Tuttle --icon tuttle/app/assets/icon/macos/AppIcon.icns --product-name Tuttle --product-version 1.0`
2. run the resulting binary distribution from the command line and watch for errors in the logs

**Comment by clstaudt** [comment]
#217

**Comment by clstaudt** [comment]
When running the bundled executable:

```
Traceback (most recent call last):
  File "app/app.py", line 14, in <module>
    from auth.view import ProfileScreen, SplashScreen
ModuleNotFoundError: No module named 'auth'
[46878] Failed to execute script 'app' due to unhandled exception: No module named 'auth'
[46878] Traceback:
Traceback (most recent call last):
  File "app/app.py", line 14, in <module>
    from auth.view import ProfileScreen, SplashScreen
ModuleNotFoundError: No module named 'auth'
```

**Comment by clstaudt** [comment]
@vlad-ed-git  An attempt at restructuring:

https://github.com/tuttle-dev/tuttle/tree/dev-packaging

To test that imports are correct without packaging every time, run from another directory, e.g.:

```
python ~/Documents/Work/Projects/PrototypeFund/Dev/tuttle/app.py        
```

It seems to me like every local import in the app code needs to be touched, rewritten as a relative import:


```python 
from ..auth.intent import AuthIntent
from ..core import utils, views
from ..core.abstractions import TView, TViewParams
```

One reason why I wasn't a fan of a large number of submodules. Do you see an alternative to this?
